[package]
name = "dji4g-windows-platform"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
dji4g-at-protocol = { path = "../at-protocol" }
dji4g-domain = { path = "../domain" }
dji4g-ipc = { path = "../ipc" }

[target.'cfg(windows)'.dependencies]
native-tls = "0.2.14"
socket2 = "0.6.1"
tokio = { version = "1.53.1", features = ["rt", "time"] }
windows = { version = "0.62.2", features = [
  "Foundation",
  "Foundation_Collections",
  "Networking_Connectivity",
  "Networking_NetworkOperators",
  "Win32_System_WinRT",
] }
windows-future = "0.3.2"
windows-sys = { version = "0.61.2", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_Security_Authorization",
  "Win32_Security_Cryptography",
  "Win32_Security_WinTrust",
  "Win32_Storage_FileSystem",
  "Win32_NetworkManagement_Dns",
  "Win32_NetworkManagement_IpHelper",
  "Win32_NetworkManagement_Ndis",
  "Win32_Networking_WinSock",
  "Win32_System_IO",
  "Win32_System_Pipes",
  "Win32_System_Registry",
  "Win32_System_Threading",
  "Win32_System_SystemInformation",
  "Win32_System_LibraryLoader",
  "Win32_Graphics_Gdi",
  "Win32_UI_Controls_Dialogs",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
] }
